# Generated by Django 6.0.4 on 2026-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
